export interface IallCategories {
  Level: number;
  Code: string;
  ParentCode: null;
  ParentId: number;
  ItemGroupImage: null;
  IsParent: boolean;
  Tbl006ID: number;
  DiscRate: number;
  IsNegativeSelling: boolean;
  Type: number;
  ItemGroupType: number;
  Item: Item[];
  PrinterName: string;
  ItemGroupBranches: ItemGroupBranchElement[];
  Id: number;
  No: number;
  Guid: string;
  NameAr: string;
  NameEn: null;
  BranchId: number;
  BranchName: string;
  CompanyId: number;
  CompanyName: null;
  DocRefGuid: string;
  IsActive: boolean;
  CreatedDate: Date;
  CreatedBy: CreatedBy;
  IsUpdated: boolean;
  LastUpdatedBy: null;
  LastUpdatedDate: Date;
  UpdatedCount: number;
  IsCanceled: boolean;
  CancelById: number;
  CancelBy: null;
  Notes: null;
  CancelDate: Date;
  ModifyById: null;
  ModifyByName: null;
  LastModifiedDate: Date;
  ModifyCount: number;
  updateFlag: null;
}

export enum CreatedBy {
  AbtkarAdmin = 'AbtkarAdmin',
  Admin = 'Admin',
  Support = 'SUPPORT',
  Support2 = 'SUPPORT2',
}

export interface Item {
  Code: string;
  GroupGuid: string;
  ItemGroupGuid: string;
  ItemGroupCode: null | string;
  ItemGroupId: number;
  Type: number;
  ItemType: number;
  RecipeItems: null;
  CouponItems: CouponItem[];
  NotTaxable: boolean;
  NotDiscountable: boolean;
  ExpiryDateRequired: boolean;
  MaxLimit: number;
  MinLimit: number;
  Category: string;
  CardImage: null | string;
  TBL007ID: number;
  SmallestUnit: number;
  TotalInQty: number;
  TotalOutQty: number;
  Balance: number;
  Vat: number;
  ItemUnits: ItemUnit[];
  ChoseUnite: null;
  LessQuantity: number;
  OrderLimit: number;
  greatestQuantity: number;
  DiscountTax: number;
  SerialNo: number;
  TypeOfProfit: number;
  ProfitRate: number;
  valueOfProfit: number;
  ProductCompany: null;
  ProductDescription: null;
  DescriptionNotes: null;
  ModelType: null;
  Model: null;
  IsModelRepeated: boolean;
  IsModelTypeRepeated: boolean;
  SupplierId: number;
  SupplierName: null;
  HomeCountry: null;
  CustomsCode: null;
  CartonSize: null;
  ColorId: number;
  Color: null;
  DealingExpiryDate: boolean;
  HasBonus: boolean;
  IsTobago: boolean;
  TobagoVat: number;
  TobagoVatAmount: number;
  Imeges: null;
  ItemPlace: number;
  Description: null;
  HowToUse: null;
  Specifications: null;
  Opinions: null;
  Id: number;
  No: number;
  Guid: string;
  NameAr: string;
  NameEn: null | string;
  BranchId: number;
  BranchName: null;
  CompanyId: number;
  CompanyName: null;
  DocRefGuid: string;
  IsActive: boolean;
  CreatedDate: Date;
  CreatedBy: CreatedBy;
  IsUpdated: boolean;
  LastUpdatedBy: null;
  LastUpdatedDate: Date;
  UpdatedCount: number;
  IsCanceled: boolean;
  CancelById: number;
  CancelBy: null;
  Notes: null;
  CancelDate: Date;
  ModifyById: null;
  ModifyByName: CreatedBy | null;
  LastModifiedDate: Date;
  ModifyCount: number;
  updateFlag: null;
}

export interface CouponItem {
  ItemId: number;
  CouponItemId: number;
  CouponItemUnitId: number;
  CouponItemUnitName: string;
  CouponUnitId: number;
  CouponUnitName: string;
  CouponItemName: string;
  Quantity: number;
  Vat: number;
  Price: number;
  Id: number;
  No: number;
  Guid: string;
  NameAr: null;
  NameEn: null;
  BranchId: number;
  BranchName: null;
  CompanyId: number;
  CompanyName: null;
  DocRefGuid: string;
  IsActive: boolean;
  CreatedDate: Date;
  CreatedBy: null;
  IsUpdated: boolean;
  LastUpdatedBy: null;
  LastUpdatedDate: Date;
  UpdatedCount: number;
  IsCanceled: boolean;
  CancelById: number;
  CancelBy: null;
  Notes: null;
  CancelDate: Date;
  ModifyById: null;
  ModifyByName: null;
  LastModifiedDate: Date;
  ModifyCount: number;
  updateFlag: null;
}

export interface ItemUnit {
  Code: string;
  UnitId: number;
  UnitName: string;
  UnitCode: null | string;
  ManualCode: string;
  Barcode: null | string;
  Gtin: null;
  Weight: number;
  Value: number;
  Factor: number;
  TaxRatio: number;
  MaxLimit: number;
  MinLimit: number;
  Price: number;
  DefaultCost: number;
  Vat: number;
  PriceTax: number;
  StanderCost: number;
  StanderCostTax: number;
  SupplierId: number;
  ColorId: number;
  Color: null;
  ItemId: number;
  ItemCode: string;
  ItemGroupId: number;
  ItemGroupGuid: string;
  Qty: number;
  WA: number;
  ItemPlace: number;
  Description: null;
  HowToUse: null;
  Specifications: null;
  Opinions: null;
  ModelType: null;
  Model: null;
  ItemImages: ItemGroupBranchElement[];
  ItemInStorageDetails: null;
  ItemsSpare: null;
  DealingExpiryDate: boolean;
  IsTobago: boolean;
  TobagoVat: number;
  TobagoVatAmount: number;
  Id: number;
  No: number;
  Guid: string;
  NameAr: string;
  NameEn: NameEn | null;
  BranchId: number;
  BranchName: null;
  CompanyId: number;
  CompanyName: null;
  DocRefGuid: string;
  IsActive: boolean;
  CreatedDate: Date;
  CreatedBy: null;
  IsUpdated: boolean;
  LastUpdatedBy: null;
  LastUpdatedDate: Date;
  UpdatedCount: number;
  IsCanceled: boolean;
  CancelById: number;
  CancelBy: null;
  Notes: null;
  CancelDate: Date;
  ModifyById: null;
  ModifyByName: null;
  LastModifiedDate: Date;
  ModifyCount: number;
  updateFlag: null;
}

export interface ItemGroupBranchElement {
  ItemUnitId?: number;
  ImagePath?: string;
  Image?: string;
  Id: number;
  No: number;
  Guid: string;
  NameAr: null;
  NameEn: null;
  BranchId: number;
  BranchName: null | string;
  CompanyId: number;
  CompanyName: null;
  DocRefGuid: string;
  IsActive: boolean;
  CreatedDate: Date;
  CreatedBy: null;
  IsUpdated: boolean;
  LastUpdatedBy: null;
  LastUpdatedDate: Date;
  UpdatedCount: number;
  IsCanceled: boolean;
  CancelById: number;
  CancelBy: null;
  Notes: null;
  CancelDate: Date;
  ModifyById: null;
  ModifyByName: CreatedBy | null;
  LastModifiedDate: Date;
  ModifyCount: number;
  updateFlag: null;
  ItemGroupId?: number;
  ItemGroupCode?: string;
  ItemGroupName?: string;
}

export enum NameEn {
  Empty = ' - ',
  ToyotaCamryUnit = 'toyota camry - Unit',
  Unit = ' - Unit',
}
